<?php
// IceHrm Web Setup Fixer v3 - Direct Write Edition
error_reporting(E_ALL);
ini_set('display_errors', 1);

$baseDir = __DIR__;
$appDir = $baseDir . '/app';
$configDest = $appDir . '/config.php';
$dataDir = $appDir . '/data';

$messages = [];
$action = $_POST['action'] ?? '';

function logMsg($msg, $isError = false)
{
    global $messages;
    $class = $isError ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800';
    $icon = $isError ? '❌' : '✅';
    $messages[] = "<div class='$class p-3 rounded mb-2 border'>$icon $msg</div>";
}

// THE CORRECT CONFIG CONTENT (Hardcoded to avoid copy errors)
$correctConfig = <<<'EOD'
<?php
/**
 * IceHrm Production Configuration - Generated by Web Setup
 */
ini_set('error_log', dirname(__FILE__) . '/data/icehrm.log');
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT);

// Application Settings
if (!defined('APP_NAME')) define('APP_NAME', 'WishLuv HR Patna - HR Management System');
if (!defined('FB_URL')) define('FB_URL', 'https://www.facebook.com/wishluvhrpatna');
if (!defined('TWITTER_URL')) define('TWITTER_URL', 'https://twitter.com/wishluvhrpatna');

// Client Configuration
if (!defined('CLIENT_NAME')) define('CLIENT_NAME', 'app');
if (!defined('APP_BASE_PATH')) define('APP_BASE_PATH', dirname(__FILE__) . '/');
if (!defined('CLIENT_BASE_PATH')) define('CLIENT_BASE_PATH', APP_BASE_PATH);

// Base URL
if (!defined('BASE_URL')) define('BASE_URL', 'https://hrms.wishluvbuildcon.com/');
if (!defined('CLIENT_BASE_URL')) define('CLIENT_BASE_URL', BASE_URL . 'app/');

// Database Configuration
if (!defined('APP_DB')) define('APP_DB', 'u743570205_wishluvhrpatna');
if (!defined('APP_USERNAME')) define('APP_USERNAME', 'u743570205_wishluvhrpatna');
if (!defined('APP_PASSWORD')) define('APP_PASSWORD', 'Anuj@2025@2026');
if (!defined('APP_HOST')) define('APP_HOST', 'localhost');
if (!defined('APP_CON_STR')) define('APP_CON_STR', 'mysqli://' . APP_USERNAME . ':' . APP_PASSWORD . '@' . APP_HOST . '/' . APP_DB);

// File Upload Settings
if (!defined('FILE_TYPES')) define('FILE_TYPES', 'jpg,png,jpeg,gif,pdf,doc,docx,xls,xlsx,txt,zip');
if (!defined('MAX_FILE_SIZE_KB')) define('MAX_FILE_SIZE_KB', 10 * 1024);

// Timezone
date_default_timezone_set('Asia/Kolkata');

// Session
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.cookie_secure', 0);

// Security
if (!defined('SESSION_EXPIRE_TIME')) define('SESSION_EXPIRE_TIME', 3600);
EOD;

if ($action === 'fix') {
    // 1. Direct Write Config
    if (file_put_contents($configDest, $correctConfig)) {
        logMsg("FIXED: Directly wrote corrected configuration to app/config.php");
    } else {
        logMsg("Error: Could not write to app/config.php. Check permissions!", true);
    }

    // 2. Fix Directory
    if (!is_dir($dataDir)) {
        mkdir($dataDir, 0755, true);
        logMsg("Created app/data directory");
    }

    // 3. Permissions
    @chmod($configDest, 0644);
    @chmod($dataDir, 0755);
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IceHrm Ultimate Fixer</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-900 min-h-screen flex items-center justify-center p-4">
    <div class="bg-white p-8 rounded-lg shadow-2xl max-w-lg w-full">
        <h1 class="text-3xl font-bold mb-2 text-gray-800">🛡️ Ultimate Fixer</h1>
        <p class="mb-6 text-gray-600">This tool will ignore all server files and write a fresh, 100% correct config file
            directly.</p>

        <?php if (!empty($messages)): ?>
            <div class="mb-6">
                <?php foreach ($messages as $msg)
                    echo $msg; ?>
            </div>

            <div class="mt-6 border-t pt-4">
                <p class="text-center font-bold text-gray-700 mb-2">🚀 Now Try Opening:</p>
                <div class="grid grid-cols-2 gap-4">
                    <a href="/app/login.php" target="_blank"
                        class="block text-center w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded transition">
                        Login Page
                    </a>
                    <a href="/app/install/" target="_blank"
                        class="block text-center w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-4 rounded transition">
                        Installer
                    </a>
                </div>
            </div>
        <?php else: ?>
            <form method="post">
                <input type="hidden" name="action" value="fix">
                <button type="submit"
                    class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-4 px-4 rounded shadow-lg transform transition hover:scale-105">
                    ✨ WRITE FRESH CONFIG
                </button>
            </form>
        <?php endif; ?>
    </div>
</body>

</html>